name: $(Date:yyyyMMdd).$(Rev:r)

stages:
  - stage: static_analysis
    jobs:
    - job: flake8_linux_py36
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: templates/base/run-linter.yml
          parameters:
            pyVersion: '3.6'

  - stage: unit_tests
    dependsOn: static_analysis
    jobs:
      - template: templates/run-tests-on-multiple-os-py.yml
        parameters:
          pyVersions: ['3.6']
          testTypes: ['unit', 'io']
          imageOSs: ['ubuntu-18.04']  # 'windows-latest', 'macos-latest'

  - stage: e2e_tests
    dependsOn: static_analysis
    jobs:
      - template: templates/run-tests-on-multiple-os-py.yml
        parameters:
          pyVersions: ['3.6']
          testTypes: ['azure']
          imageOSs: ['ubuntu-18.04']  # 'windows-latest', 'macos-latest'

  - stage: collect_final_code_coverage
    dependsOn: 
      - unit_tests
      - e2e_tests
    jobs:
      - template: templates/merge-cov-reports.yml
