steps:
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' 
    testResultsFiles: 'junit/*.xml' 
    searchFolder: $(Build.SourcesDirectory)
    testRunTitle: $(imageName)_$(pyVersion) Build
    buildPlatform: $(imageName)
  displayName: 'Publish unit test report'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.xml'