parameters:
- name: pyVersions
  type: object
  default: ['3.6', '3.7', '3.8']
- name: testTypes
  type: object
  default: ['fast', 'slow']

jobs:
- ${{ each pyVersion in parameters.pyVersions }}:
  - job: run_tests_py${{ replace(pyVersion, '.', '_') }}
    steps:
    
    - task: UsePythonVersion@0
      inputs:
        versionSpec: ${{pyVersion}}
        addToPath: true
        architecture: 'x64'
      displayName: 'Use Python ${{pyVersion}}'

    - template: install-dependencies.yml

    - ${{ each testType in parameters.testTypes }}:
      - template: run-tests.yml
        parameters:
          testType: ${{testType}}

    - template: publish-cov.yml