# Template for running tests on multiple Python versions and platforms

parameters:
- name: testType
  type: string
  default: all
  values:
    - slow
    - azure
    - fast
    - all

steps:
- bash: |
    if [[ '${{parameters.testType}}' == 'all' ]]
    then
      tox -e py 
    elif [[ '${{parameters.testType}}' == 'fast' ]]
    then
      tox -e py -- -m "not slow and not azure"
    else
      tox -e py -- -m "${{parameters.testType}}"
    fi
  env:
    BLOB_KEY : $(BLOB_KEY)
    SEARCH_SERVICE_KEY: $(SEARCH_SERVICE_KEY)
    COGNITIVE_SERVICE_KEY: $(COGNITIVE_SERVICE_KEY)
    COMPUTER_VISION_SUBSCRIPTION_KEY: $(COMPUTER_VISION_SUBSCRIPTION_KEY)
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Running (${{parameters.testType}}) Tests'
